site_name: wonkey-coders

#
# Navigation
#
nav:
    - Start:                              index.md
    - Demos:
        - Wonkey Examples:                examples.md
        - Community Examples:             community.md
#    - Introduction:
#        - About: about_docs.md
    - Docs:
        - User Guide:
            - docs/guide/index.md
            - The 'wake' compiler:        docs/guide/wake.md
            - Target SDKs:
                - docs/guide/sdks/index.md
                - Android:                docs/guide/sdks/android.md
                - Emscripten:             docs/guide/sdks/emscripten.md
                - iOS:                    docs/guide/sdks/ios.md
                - Linux:                  docs/guide/sdks/linux.md
                - macOS:                  docs/guide/sdks/mac.md
                - Raspberry Pi:           docs/guide/sdks/raspberry.md
                - Windows:                docs/guide/sdks/windows.md
        - Language Reference:
            - docs/lang/index.md
            - Imports:                    docs/lang/import.md
            - Assets:                     docs/lang/assets.md
            - Comments:                   docs/lang/comments.md
            - Namespaces:                 docs/lang/namespace.md
            - Functions:
                - Global functions:       docs/lang/function.md
                - Lambda functions:       docs/lang/lambda.md
                - Function overloading:   docs/lang/function-overloading.md
                - Function values:        docs/lang/function-values.md
            - Expressions:
                - docs/lang/expressions.md
                - Operators:              docs/lang/operators.md
                - Casting:                docs/lang/cast.md
                - Type balancing:         docs/lang/type-balancing.md
            - Variables:                  docs/lang/variables.md
            - Strings:                    docs/lang/string.md
            - Variants:                   docs/lang/variant.md
            - Aliases:                    docs/lang/alias.md
            - Basic types:                docs/lang/datatypes.md
            - Compound types:
                - docs/lang/compound-types.md
                - Arrays:                 docs/lang/array.md
                - Enums:                  docs/lang/enum.md
                - Pointers:               docs/lang/pointer.md
                - Classes:                docs/lang/class.md
                - Structs:                docs/lang/struct.md
                - Interfaces:             docs/lang/interface.md
                - Fields:                 docs/lang/field.md
                - Methods:                docs/lang/method.md
                - Class/Struct Functions: docs/lang/class-function.md
                - Properties:             docs/lang/property.md
                - Conversion Operators:   docs/lang/conversion-operators.md
                - Operator overloading:   docs/lang/operator-overloading.md
                - Inheritance:            docs/lang/extends.md
                - Extensions:             docs/lang/extension.md
                - Encapsulation:          docs/lang/encapsulation.md
            - Generics:
                - docs/lang/generics.md
                - Generic Function:       docs/lang/generic-function.md
                - Generic Class:          docs/lang/generic-class.md
                - Generic Struct:         docs/lang/generic-struct.md
                - Generic Interface:      docs/lang/generic-interface.md
            - Conditional statements:     docs/lang/conditional-statements.md
            - Loop statements:            docs/lang/loop-statements.md
            - The Preprocessor:           docs/lang/preprocessor.md
            - Error handling:             docs/lang/error-handling.md
            - Weak references:            docs/lang/weak-references.md
            - Reflection:                 docs/lang/reflection.md
            - Modules:                    docs/lang/modules.md
            - Native code:                docs/lang/native-code.md
            - Misc:                       docs/lang/misc.md
        - Modules Reference:
            - docs/modules/index.md
            - wonkey:
                - docs/modules/wonkey/wonkey-module.md
                - debug:                   docs/modules/wonkey/wonkey-debug.md
                - gc:                      docs/modules/wonkey/wonkey-gc.md
                - math:                    docs/modules/wonkey/wonkey-math.md
                - types:                   docs/modules/wonkey/wonkey-types.md
            - std:
                - docs/modules/std/std-module.md
                - permissions:             docs/modules/std/std-permissions.md
                - requesters:              docs/modules/std/std-requesters.md
                - socket:                  docs/modules/std/std-socket.md
                - digest:                  docs/modules/std/std-digest.md
                - base64:                  docs/modules/std/std-base64.md
                - zipfile:                 docs/modules/std/std-zipfile.md
                - jsonify:                 docs/modules/std/std-jsonify.md
                - json:                    docs/modules/std/std-json.md
                - stringio:                docs/modules/std/std-stringio.md
                - random:                  docs/modules/std/std-random.md
                - filesystem:              docs/modules/std/std-filesystem.md
                - process:                 docs/modules/std/std-process.md
                - fiber:                   docs/modules/std/std-fiber.md
                - timer:                   docs/modules/std/std-timer.md
                - time:                    docs/modules/std/std-time.md
                - async:                   docs/modules/std/std-async.md
                - audio:                   docs/modules/std/std-audio.md
                - graphics:                docs/modules/std/std-graphics.md
                - geom:                    docs/modules/std/std-geom.md
                - memory:                  docs/modules/std/std-memory.md
                - stream:                  docs/modules/std/std-stream.md
                - resource:                docs/modules/std/std-resource.md
                - collections:             docs/modules/std/std-collections.md
            - libc:                        docs/modules/libc/libc-module.md
            - thread:                      docs/modules/thread/thread-module.md
            - reflection:                  docs/modules/reflection/reflection-module.md
            - mojo:
                - docs/modules/mojo/mojo-module.md
                - audio:                   docs/modules/mojo/mojo-audio.md
                - input:                   docs/modules/mojo/mojo-input.md
                - graphics:
                    - docs/modules/mojo/mojo-graphics.md
                    - glutil:              docs/modules/mojo/mojo-graphics-glutil.md
                - app:                     docs/modules/mojo/mojo-app.md
            - mojo3d:                      docs/modules/mojo3d/mojo3d-module.md
            - mojo3d-loaders:              docs/modules/mojo3d-loaders/mojo3d-loaders-module.md
            - mojo3d-vr:                   docs/modules/mojo3d-vr/mojo3d-vr-module.md
            - mojox:                       docs/modules/mojox/mojox-module.md
            - admob:                       docs/modules/admob/admob-module.md
            - android:                     docs/modules/android/android-module.md
            - assimp:                      docs/modules/assimp/assimp-module.md
            - bullet:                      docs/modules/bullet/bullet-module.md
            - chipmunk:                    docs/modules/chipmunk/chipmunk-module.md
            - emscripten:                  docs/modules/emscripten/emscripten-module.md
            - freetype:                    docs/modules/freetype/freetype-module.md
            - gles20:                      docs/modules/gles20/gles20-module.md
            - hoedown:                     docs/modules/hoedown/hoedown-module.md
            - httprequest:                 docs/modules/httprequest/httprequest-module.md
            - iap:                         docs/modules/iap/iap-module.md
            - jni:                         docs/modules/jni/jni-module.md
            - litehtml:                    docs/modules/litehtml/litehtml-module.md
            - miniz:                       docs/modules/miniz/miniz-module.md
            - openal:                      docs/modules/openal/openal-module.md
            - opengl:                      docs/modules/opengl/opengl-module.md
            - sdl2:                        docs/modules/sdl2/sdl2-module.md
            - sdl2-mixer:                  docs/modules/sdl2-mixer/sdl2-mixer-module.md
            - sokol:                       docs/modules/sokol/sokol-module.md
            - sqlite:                      docs/modules/sqlite/sqlite-module.md
            - stb-image:                   docs/modules/stb-image/stb-image-module.md
            - stb-image-write:             docs/modules/stb-image-write/stb-image-write-module.md
            - stb-truetype:                docs/modules/stb-truetype/stb-truetype-module.md
            - stb-vorbis:                  docs/modules/stb-vorbis/stb-vorbis-module.md
            - theoraplayer:                docs/modules/theoraplayer/theoraplayer-module.md
            - tinyregex:                   docs/modules/tinyregex/tinyregex-module.md
            - tinyxml2:                    docs/modules/tinyxml2/tinyxml2-module.md
            - win32:                       docs/modules/win32/win32-module.md
            - zlib:                        docs/modules/zlib/zlib-module.md

#    - About:
#        - About: about_docs.md

#    - Wonkey Site: https://github.com/wonkey-coders/wonkey


# Theme
#
# built-in themes:
#
#     + mkdocs (default)
#     + readthedocs
#     + windmill
#     + material
theme:
    name: material
    logo: 'images/w_round.png'
    favicon: 'images/favicon.ico'
    palette:
        scheme: slate
        primary: 'black'
        accent: 'light blue'
        #primary: 'light blue'
        #accent: 'light blue'
        #primary: 'Red'
        #accent: 'Red'
#    font:
#        text: 'Ubuntu'
#        code: 'Ubuntu Mono'
#    feature:
#        tabs: true
    #highlightjs: true
    #hljs_languages:
    #    - monkey
#    use_pygments: true
    shortcuts:
        help: 191    # ?
        next: 78     # n
        previous: 80 # p
        search: 83   # s

#use_directory_urls: false
#strict: true

#
# CSS
#
extra_css:
    - 'stylesheets/extra.css'

#
# Plugins
#
plugins:
    - section-index
    - search:
        separator: '[\s\-\.]+'


#
# Extensions
#
markdown_extensions:
    - attr_list
    #- codehilite:
    #    linenums: true
    #    guess_lang: false
    - admonition
    - toc:
        permalink: "#"
        separator: "_"
    - pymdownx.arithmatex
    - pymdownx.betterem:
          smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.emoji:
        emoji_generator: !!python/name:pymdownx.emoji.to_svg
#    - pymdownx.highligth:
#        linenums: true
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde
